default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: friendzip_development
  username: postgres
  password: 123456

test:
  <<: *default
  database: friendzip_test
  username: postgres
  password: 123456

production:
  <<: *default
  database: friendzip_production
